Repository Trend-Now/Back-end, pull requests merged in 2025-09, with the labels that each got.

#124 [refactor][CCS-67] 실시간 게시판 score을 UTC 기준 시각을 사용하여 만료 시간으로 세팅하도록 변경
  backend/src/main/java/com/trend_now/backend/board/application/BoardRedisService.java
  backend/src/main/java/com/trend_now/backend/board/application/SignalKeywordJob.java
  backend/src/main/java/com/trend_now/backend/post/application/PostLikesService.java
  backend/src/test/java/com/trend_now/backend/unit/board/service/BoardsRedisServiceTest.java
Labels: 🔨 Refactor

#126 [feat][CCS-68] 네이버 뉴스와 Gemini API로 실시간 인기 검색어 등재 이유 분석하고 저장
  backend/build.gradle
  backend/src/main/java/com/trend_now/backend/board/application/BoardRedisService.java
  backend/src/main/java/com/trend_now/backend/board/application/BoardService.java
  backend/src/main/java/com/trend_now/backend/board/application/BoardSummaryService.java
  backend/src/main/java/com/trend_now/backend/board/application/SignalKeywordJob.java
  backend/src/main/java/com/trend_now/backend/board/application/SignalKeywordService.java
  backend/src/main/java/com/trend_now/backend/board/domain/BoardSummary.java
  backend/src/main/java/com/trend_now/backend/board/dto/BoardInfoDto.java
  backend/src/main/java/com/trend_now/backend/board/dto/RankChangeType.java
  backend/src/main/java/com/trend_now/backend/board/dto/Top10.java
  backend/src/main/java/com/trend_now/backend/board/repository/BoardSummaryRepository.java
  backend/src/main/java/com/trend_now/backend/client/GeminiApiClient.java
  backend/src/main/java/com/trend_now/backend/client/NaverApiClient.java
  backend/src/main/java/com/trend_now/backend/client/dto/NaverNewsResponseDto.java
  backend/src/main/java/com/trend_now/backend/config/WebClientConfig.java
  backend/src/main/java/com/trend_now/backend/config/quartz/QuartzJobConfig.java
  backend/src/main/java/com/trend_now/backend/post/domain/Post.java
  backend/src/test/java/com/trend_now/backend/integration/board/controller/BoardsControllerTest.java
  backend/src/test/java/com/trend_now/backend/integration/board/service/BoardSummaryServiceTest.java
  backend/src/test/java/com/trend_now/backend/integration/board/service/BoardsRedisServiceTest.java
  backend/src/test/java/com/trend_now/backend/integration/board/service/SignalKeywordServiceTest.java
  backend/src/test/java/com/trend_now/backend/integration/client/GeminiApiClientTest.java
  backend/src/test/java/com/trend_now/backend/integration/client/NaverApiClientTest.java
Labels: ✨ Feature

#129 [refactor][CCS-69] 실시간 인기 검색어 스케줄러 리팩토링과 조회 API 응답 수정
  backend/build.gradle
  backend/src/main/java/com/trend_now/backend/board/application/BoardRedisService.java
  backend/src/main/java/com/trend_now/backend/board/application/BoardService.java
  backend/src/main/java/com/trend_now/backend/board/application/BoardSummaryService.java
  backend/src/main/java/com/trend_now/backend/board/application/SignalKeywordJob.java
  backend/src/main/java/com/trend_now/backend/board/application/SignalKeywordService.java
  backend/src/main/java/com/trend_now/backend/board/application/board_summary/AsyncSummaryGeneratorService.java
  backend/src/main/java/com/trend_now/backend/board/application/board_summary/BoardSummaryService.java
  backend/src/main/java/com/trend_now/backend/board/application/board_summary/BoardSummaryTriggerService.java
  backend/src/main/java/com/trend_now/backend/board/domain/BoardSummary.java
  backend/src/main/java/com/trend_now/backend/board/dto/RealtimeBoardDto.java
  backend/src/main/java/com/trend_now/backend/board/dto/Top10WithDiff.java
  backend/src/main/java/com/trend_now/backend/board/presentation/SignalKeywordController.java
  backend/src/main/java/com/trend_now/backend/board/repository/BoardSummaryRepository.java
  backend/src/main/java/com/trend_now/backend/client/GeminiApiClient.java
  backend/src/test/java/com/trend_now/backend/integration/board/controller/BoardsControllerTest.java
  backend/src/test/java/com/trend_now/backend/integration/board/service/BoardSummaryServiceTest.java
  backend/src/test/java/com/trend_now/backend/integration/board/service/BoardsRedisServiceTest.java
  backend/src/test/java/com/trend_now/backend/integration/board/service/SignalKeywordServiceTest.java
  backend/src/test/java/com/trend_now/backend/integration/posts/service/PostLikesServiceUnitTest.java
  backend/src/test/java/com/trend_now/backend/unit/board/service/BoardsRedisServiceTest.java
Labels: ✅ Test, 📬 API, ✨ Feature, 🔨 Refactor
